parameters:
#    gallerie_media.example.class: Gallerie\MediaBundle\Example

services:
#    gallerie_media.example:
#        class: %gallerie_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
